--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
------------------------------ INTRUÇÃO SELECT  --------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- CRIAÇÃO DE REGISTROS (MASSA DE DADOS) PARA O EXERCÍCIO DA AULA
-- MASSA DE DADOS:
INSERT INTO CATEGORIA (DS_CATEGORIA) VALUES('Banco de dados');
INSERT INTO CATEGORIA (DS_CATEGORIA) VALUES('Linguagem de Programação');
INSERT INTO CATEGORIA (DS_CATEGORIA) VALUES('Containers');
INSERT INTO CATEGORIA (DS_CATEGORIA) VALUES('Devops');
INSERT INTO CATEGORIA (DS_CATEGORIA) VALUES('Devops');
INSERT INTO CATEGORIA (DS_CATEGORIA) VALUES('DEVOPS');
COMMIT;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

-- INSTRUÇÃO BÁSICA DO SQL:
SELECT *            -- SESSAO DE COLUNAS. (*) REPRESENTA TODAS AS COLUNAS DA 
                    -- TABELA.
  FROM NOME_TABELA; -- TABELA QUE SERÁ CONSULTADA.

-- EXEMPLO: BUSCANDO TODOS OS REGISTROS E TODAS AS COLUNAS DA TABELA CATEGORIA:
SELECT *
  FROM CATEGORIA;

-- EXEMPLO: ESPECIFICANDO TODAS AS COLUNAS DA TABELA:
SELECT ID_CATEGORIA, DS_CATEGORIA
  FROM CATEGORIA;

-- DISTINCT: DISTINGUI OS REGISTROS RETORNADOS NA CONSULTA. EM CASO DE REGISTROS
-- DUPLICADOS, ELE RETORNARÁ SOMENTE UM DELES.
SELECT DISTINCT *
  FROM CATEGORIA;
  
-- DISTINCT COM SOMENTE UMA COLUNA.
SELECT DISTINCT DS_CATEGORIA
  FROM CATEGORIA;

-- ALIAS DE COLUNA:  
-- EXEMPLO 01:
SELECT ID_CATEGORIA AS "Id. Categoria", DS_CATEGORIA AS "Descrição"
  FROM CATEGORIA;

-- EXEMPLO 02:  
SELECT ID_CATEGORIA AS CAT_ID, DS_CATEGORIA AS CAT_DS
  FROM CATEGORIA;
  
-- OBS: A PALAVRA "AS" É OPCIONAL.
  
-- ALIAS DE TABELA:
SELECT C.ID_CATEGORIA AS "Id. Categoria",
       C.DS_CATEGORIA AS "Descrição"
  FROM CATEGORIA C; -- (C) É O ALIAS ATRIBUIDO À TABELA CATEGORIA.
  
-- SELECT UTILIZANDO O DUAL
-- OBS: DUAL É UMA TABELA QUE UTILIZAMOS NA INSTRUÇÃO QUANDO NÃO NECESSITAMOS 
-- EXTRAIR DADOS, MAS SIM, AVALIAR UMA EXPRESSÃO, OU FAZER CHAMADA DE FUNÇÃO. 
SELECT 20*17 RESULTADO, 'STRING NO LUGAR DA COLUNA' STRING
  FROM DUAL;

-- OPERADOR DE CONCATENAÇÃO DE COLUNAS E STRINGS
SELECT 'ESSE OBJETO ' || OBJECT_NAME || ' ELE É DO TIPO: ' ||  OBJECT_TYPE
  FROM USER_OBJECTS;

