--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
---------------------- ALTERANDO A ESTRUTURA DE TABELAS ------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- TABELAS UTILIZADAS NA AULA:
CREATE TABLE TB_PESSOA(ID_PESSOA NUMBER,
                       NM_PESSOA VARCHAR2(50),
CONSTRAINT TB_PESSOA_PK PRIMARY KEY(ID_PESSOA));

CREATE SEQUENCE TB_AULA_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TB_AULA(ID_AULA NUMBER DEFAULT TB_AULA_SEQ.NEXTVAL NOT NULL,
                     DS_AULA VARCHAR2(50),
                     DT_CADASTRO DATE DEFAULT SYSDATE NOT NULL,
                     ST_ATIVO CHAR(1) DEFAULT 'N' NOT NULL,
                     ID_PESSOA NUMBER,
CONSTRAINT TB_AULA_PK PRIMARY KEY (ID_AULA));

-- 1) ADICIONAR COLUNAS NOVAS
ALTER TABLE TB_PESSOA ADD DT_NASCIMENTO DATE;

-- 2) REMOVER COLUNAS
ALTER TABLE TB_PESSOA DROP COLUMN DT_NASCIMENTO;

-- 3) MODIFICAR COLUNAS EXISTENTES
ALTER TABLE TB_PESSOA MODIFY NM_PESSOA VARCHAR(100);

-- 4) ADICIONAR UMA CONSTRAINT NOT NULL COM MODIFY
ALTER TABLE TB_PESSOA MODIFY NM_PESSOA NOT NULL;

-- 5) ADICIONAR UMA CONSTRAINT
ALTER TABLE TB_AULA ADD CONSTRAINT AULA_FK02 FOREIGN KEY (ID_PESSOA) 
REFERENCES TB_PESSOA(ID_PESSOA);

-- 6) REMOVER UMA CONSTRAINT
ALTER TABLE TB_PESSOA DROP CONSTRAINT AULA_FK01;

-- 7) DESATIVAR UMA CONSTRAINT
ALTER TABLE TB_AULA ENABLE CONSTRAINT AULA_FK02;