--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-------------------------------- JOIN ------------------------------------------
-------------------------- LEFT OUTER JOIN -------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
/** JOINS INTERNAS: ESSE TIPO DE JOIN RETORNA SOMENTE OS REGISTROS QUE POSSUEM
    CORRESPONDÊNCIAS NAS TABELAS ENVOLVIDAS NO JOIN. REGISTROS QUE NÃO POSSUEM
    REFERENCIA, NÃO SÃO RETORNADOS NAS CONSULTAS DE JOIN INTERNA.
    OS TRÊS TIPOS DE JOINS ABAIXO, SÃO DO TIPO JOIN INTERNA: **/

-- NATURALA JOIN
SELECT *
  FROM ALUNO NATURAL JOIN ESCOLARIDADE;
  
-- JOIN COM A CLÁUSULA USING
SELECT *
  FROM ALUNO JOIN ESCOLARIDADE USING (ID_ESCOLARIDADE);
  
-- JOIN COM A CLÁUSULA ON
SELECT *
  FROM ALUNO A JOIN ESCOLARIDADE E
   ON (A.ID_ESCOLARIDADE = E .ID_ESCOLARIDADE);
   
/** JOINS EXTERNAS: SÃO JOINS QUE FORÇAM O RETORNO DE REGISTROS QUE NÃO POSSUEM 
    REFERÊNCIA NAS TABELAS TANTO À DIREITA, QUANTO À ESQUERDA OU EM AMBOS.
    TEMOS OS TIPOS:
 
       1) LEFT OUTER JOIN: RETORNA AS LINHAS DA TABELA À 
          ESQUERDA, MESMO QUE NÃO TENHA REFERÊNCIA NA TABELA Á DIREITA.
          
       2) RIGHT OUTER JOIN: RETORNA AS LINHAS DA TABELA À DIREITA, MESMO QUE
          NÃO POSSUA REFERÊNCIA NA TABELA À ESQUERDA.
          
       3) FULL OUTER JOIN: RETORNA AS LINHAS DAS TABELAS TANTO À DIREITA QUANTO
          À ESQUERDA, MESMO QUE NÃO EXISTA REFERÊNCIA EM AMBOS OS LADOS.

********************************************************************************
****************************** LEFT OUTER JOIN *********************************
********************************************************************************

NO EXEMPLO ABAIXO, OS REGISTROS COM IDS: 2,3,4 E 7 DA TABELA ESCOLARIDADE NÃO 
POSSUEM REFERÊNCIA NA TABELA ALUNO. NUMA JOIN INTERNA ESSES REGISTROS NÃO SÃO 
RETORNADOS, JÁ NA  JOIN EXTERNA À ESQUERDA (LEFT OUTER JOIN) ESSES REGISTROS 
SERÃO RETORNADOS. AS COLUNAS QUE NÃO POSSUEM REFERÊNCIA NA TABELA ALUNO, 
RETORNARAM COM VALORES "NULL":
**/


SELECT *
  FROM ESCOLARIDADE E LEFT OUTER JOIN -- JOIN EXTERNA A ESQUERDA
       ALUNO A                        -- ALUNO ESTÁ A DIREITA DA QUERY
   ON (E.ID_ESCOLARIDADE = A.ID_ESCOLARIDADE);

/**
1) E SE EU COLOCAR A TABELA ESCOLARIDADE À DIREITA DA QUERY, IRÁ FUNCIONAR, OU
   SEJA, IRÁ TRAZER OS REGISTROS DA TABELA ESCOLARIDADE QUE NÃO POSSUEM 
   REFERÊNCIA NA TABELA ALUNO?
   A CONSULTA IRÁ FUNCIONAR, MAS NÃO TRARÁ O RESULTADO ESPERADO.
**/

SELECT *
  FROM ALUNO A LEFT OUTER JOIN -- JOIN EXTERNA A ESQUERDA
       ESCOLARIDADE E          -- ESCOLARIDADE À DIREITA
   ON (E.ID_ESCOLARIDADE = A.ID_ESCOLARIDADE);
