--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
----------------------------- OPERADORES DE ------------------------------------
--------------------------- CONJUNTO - UNION -----------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- 1) O NÚMERO DE COLUNAS DE AMBAS AS CONSULTAS DEVEM SER IGUAIS
-- 2) O OPERADOR UNION ELE DESCARTA VALORES REPETIDOS
-- 3) VALORES NULOS NÃO SÃO IGNORADOS

-- CONSULTA QUE RETORNA DADOS DOS ALUNOS
SELECT P.ID_PESSOA, P.NM_PRIMEIRO_NOME, P.NM_SOBRENOME, P.DT_NASCIMENTO, 
       'ALUNO' AS TIPO_PESSOA, A.ID_ESCOLARIDADE
  FROM PESSOA P JOIN
       ALUNO A 
   ON (P.ID_PESSOA = A.ID_ALUNO)
UNION
-- CONSULTA QUE RETORNA DADOS DOS PROFESSORES
SELECT P.ID_PESSOA, P.NM_PRIMEIRO_NOME, P.NM_SOBRENOME, P.DT_NASCIMENTO, 
       'PROFESSOR' AS TIPO_PESSOA, NULL AS "ID_ESCOLARIDADE"
  FROM PESSOA P JOIN
       PROFESSOR PP 
   ON (P.ID_PESSOA = PP.ID_PROFESSOR)
UNION
-- CONSULTA QUE RETORNA DADOS DOS ADMINISTRADORES
SELECT P.ID_PESSOA, P.NM_PRIMEIRO_NOME, P.NM_SOBRENOME, P.DT_NASCIMENTO, 
       'ADMINISTRADOR' AS TIPO_PESSOA, NULL AS "ID_ESCOLARIDADE"
  FROM PESSOA P JOIN
       ADMINISTRADOR A 
   ON (P.ID_PESSOA = A.ID_ADMINISTRADOR)
UNION
-- ESSA CONSULTA FOI REPETIDA PARA TESTARMOS O DESCARTE DE REGISTROS DUPLICADOS.
SELECT P.ID_PESSOA, P.NM_PRIMEIRO_NOME, P.NM_SOBRENOME, P.DT_NASCIMENTO, 
       'ADMINISTRADOR' AS TIPO_PESSOA, NULL AS "ID_ESCOLARIDADE"
  FROM PESSOA P JOIN
       ADMINISTRADOR A 
   ON (P.ID_PESSOA = A.ID_ADMINISTRADOR)
ORDER BY TIPO_PESSOA;